# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokoj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenia',
            name='opis',
            field=models.TextField(help_text='Opis Og\u0142oszenia'),
        ),
    ]
