# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokoj', '0002_auto_20170403_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogloszenia',
            options={'verbose_name': 'og\u0142oszenie', 'verbose_name_plural': 'og\u0142oszenia'},
        ),
    ]
